Repository statsmodels/statsmodels, pull requests merged in 2019-07, with the labels that each got.

#5892 BUG: fix pandas compat
  statsmodels/compat/pandas.py
Labels: backport

#5903 BUG: Fix kwargs update bug in linear model fit_regularized
  statsmodels/regression/linear_model.py
Labels: backport

#5895 DOC: improvements to BayesMixedGLM docs, argument checking
  statsmodels/genmod/bayes_mixed_glm.py
  statsmodels/genmod/tests/test_bayes_mixed_glm.py
Labels: Documentation, backport, comp-genmod

#5918 MAINT: Backport "BUG: TVTP for Markov regression"
  statsmodels/tsa/regime_switching/markov_switching.py
  statsmodels/tsa/regime_switching/tests/test_markov_regression.py
Labels: backport, comp-tsa

#5898 ENH: use class to define MixedLM variance components structure
  statsmodels/regression/mixed_linear_model.py
Labels: comp-regression, maintenance

#5921 BUG: Ensure exponential smoothers has continuous double data
  statsmodels/tsa/holtwinters.py
  statsmodels/tsa/tests/test_holtwinters.py
Labels: backport, type-bug

#5915 ENH: state space: add methods to apply fitted parameters to new observations or new dataset
  docs/source/_static/images/statespace_forecasting.png
  docs/source/examples/landing.json
  examples/notebooks/statespace_forecasting.ipynb
  statsmodels/tsa/statespace/dynamic_factor.py
  statsmodels/tsa/statespace/kalman_filter.py
  statsmodels/tsa/statespace/mlemodel.py
  statsmodels/tsa/statespace/sarimax.py
  statsmodels/tsa/statespace/structural.py
  statsmodels/tsa/statespace/tests/test_dynamic_factor.py
  statsmodels/tsa/statespace/tests/test_sarimax.py
  statsmodels/tsa/statespace/tests/test_structural.py
  statsmodels/tsa/statespace/tests/test_varmax.py
  statsmodels/tsa/statespace/varmax.py
Labels: comp-tsa, type-enh

#5757 MAINT: Remove docstring'd-out traceback for code that no longer raises
  lint.sh
  statsmodels/sandbox/stats/ex_multicomp.py
  statsmodels/sandbox/stats/multicomp.py
  statsmodels/sandbox/stats/tests/test_multicomp.py
Labels: type-cleanup

#5933 MAINT: Fix test that fails with positive probability
  statsmodels/sandbox/distributions/tests/test_multivariate.py
Labels: backport

#5768 WIP/TST: enable/mark mangled/commented-out tests
  .travis.yml
  lint.sh
  setup.cfg
  statsmodels/base/tests/test_data.py
  statsmodels/datasets/tests/test_utils.py
  statsmodels/discrete/tests/test_constrained.py
  statsmodels/discrete/tests/test_discrete.py
  statsmodels/gam/smooth_basis.py
  statsmodels/genmod/tests/test_glm.py
  statsmodels/graphics/tests/test_gofplots.py
  statsmodels/iolib/tests/test_summary_old.py
  statsmodels/nonparametric/tests/test_kde.py
  statsmodels/nonparametric/tests/test_kernel_regression.py
  statsmodels/nonparametric/tests/test_kernels.py
  statsmodels/regression/tests/test_glsar_stata.py
  statsmodels/regression/tests/test_regression.py
  statsmodels/robust/tests/test_scale.py
  statsmodels/sandbox/distributions/mv_normal.py
  statsmodels/sandbox/regression/tests/test_gmm.py
  statsmodels/sandbox/tests/test_gam.py
  statsmodels/stats/libqsturng/tests/test_qsturng.py
  statsmodels/stats/tests/test_diagnostic.py
  statsmodels/stats/tests/test_inter_rater.py
  statsmodels/stats/tests/test_power.py
  statsmodels/stats/tests/test_tost.py
  statsmodels/stats/tests/test_weightstats.py
  statsmodels/tools/tests/test_decorators.py
  statsmodels/tools/tests/test_grouputils.py
  statsmodels/tools/tests/test_numdiff.py
  statsmodels/tools/tests/test_tools.py
  statsmodels/tsa/base/tests/test_tsa_indexes.py
  statsmodels/tsa/regime_switching/tests/test_markov_autoregression.py
  statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
  statsmodels/tsa/statespace/tests/test_kalman.py
  statsmodels/tsa/statespace/tests/test_models.py
  statsmodels/tsa/tests/test_arima.py
  statsmodels/tsa/tests/test_holtwinters.py
  statsmodels/tsa/tests/test_stattools.py
  statsmodels/tsa/vector_ar/tests/test_var.py
Labels: type-cleanup

#5935 CLN: port parts of #5220
  statsmodels/compat/pandas.py
  statsmodels/tsa/vector_ar/irf.py
  statsmodels/tsa/vector_ar/svar_model.py
  statsmodels/tsa/vector_ar/tests/test_svar.py
  statsmodels/tsa/vector_ar/util.py
  statsmodels/tsa/vector_ar/var_model.py
Labels: backport

#5944 BUG: Restore ResettableCache
  statsmodels/tools/decorators.py
Labels: backport

#5951 BUG: Fix mosaic plot with missing category
  statsmodels/graphics/mosaicplot.py
  statsmodels/graphics/tests/test_mosaicplot.py
Labels: backport

#5926 Add STL decomposition for time series
  docs/source/tsa.rst
  examples/notebooks/stl_decomposition.ipynb
  lint.sh
  setup.py
  statsmodels/datasets/elec_equip/__init__.py
  statsmodels/datasets/elec_equip/data.py
  statsmodels/datasets/elec_equip/elec_equip.csv
  statsmodels/tsa/_stl.pyx
  statsmodels/tsa/seasonal.py
  statsmodels/tsa/tests/results/stl-fixed.f90
  statsmodels/tsa/tests/results/stl_co2
  statsmodels/tsa/tests/results/stl_co2.csv
  statsmodels/tsa/tests/results/stl_test_data.f90
  statsmodels/tsa/tests/results/stl_test_results.csv
  statsmodels/tsa/tests/test_stl.py
Labels: Major Feature

#5610 BUG: Lilliefors min nobs not set
  statsmodels/stats/_lilliefors.py
  statsmodels/stats/_lilliefors_critical_values.py
  statsmodels/stats/tabledist.py
  statsmodels/stats/tests/results/lilliefors_critical_value_simulation.py
  statsmodels/stats/tests/test_diagnostic.py
  statsmodels/stats/tests/test_lilliefors.py
  statsmodels/stats/tests/test_tabledist.py
Labels: type-bug

#5692 MAINT: remove sandbox.formula, supplanted by patsy
  statsmodels/sandbox/contrast_old.py
  statsmodels/sandbox/examples/ex_formula.py
  statsmodels/sandbox/examples/ex_formula_factor.py
  statsmodels/sandbox/formula.py
  statsmodels/sandbox/tests/test_formula.py
  statsmodels/sandbox/utils_old.py
Labels: type-cleanup

#6005 Ignore warns on 32 bit linux
  statsmodels/base/tests/test_generic_methods.py
  statsmodels/compat/platform.py
Labels: build, maintenance

#5998 Replace alpha=0.05 with alpha=alpha
  statsmodels/sandbox/stats/multicomp.py
Labels: backport, type-bug

#5963 ENH: Functional SIR
  statsmodels/regression/dimred.py
  statsmodels/regression/tests/test_dimred.py
Labels: Major Feature

#6044 DOC: Fix notebook due to pandas index change
  examples/notebooks/statespace_seasonal.ipynb
Labels: backport

#5735 ENH: Allow fixing parameters in state space models
  docs/source/_static/images/statespace_fixed_params.png
  docs/source/examples/landing.json
  examples/notebooks/statespace_dfm_coincident.ipynb
  examples/notebooks/statespace_fixed_params.ipynb
  statsmodels/tsa/statespace/dynamic_factor.py
  statsmodels/tsa/statespace/mlemodel.py
  statsmodels/tsa/statespace/sarimax.py
  statsmodels/tsa/statespace/structural.py
  statsmodels/tsa/statespace/tests/test_fixed_params.py
  statsmodels/tsa/statespace/varmax.py
Labels: Major Feature, comp-tsa, comp-tsa-statespace, type-enh
