Repository statsmodels/statsmodels, pull requests merged in 2020-01, with the labels that each got.

#6401 ENH: Distance dependence measures
  docs/source/release/version0.11.rst
  docs/source/stats.rst
  statsmodels/stats/dist_dependence_measures.py
  statsmodels/stats/tests/test_dist_dependant_measures.py
Labels: comp-stats, type-enh

#6415 BUG: RecursiveLS should not allow `fix_params` method.
  statsmodels/regression/recursive_ls.py
  statsmodels/regression/tests/test_recursive_ls.py
Labels: comp-tsa-statespace, type-bug

#6414 CLN: Fixes for future SciPY and pandas
  lint.sh
  statsmodels/base/data.py
  statsmodels/base/tests/test_generic_methods.py
  statsmodels/compat/scipy.py
  statsmodels/graphics/regressionplots.py
  statsmodels/graphics/tests/test_regressionplots.py
  statsmodels/sandbox/predict_functional.py
  statsmodels/tsa/holtwinters.py
  statsmodels/tsa/tests/test_holtwinters.py
Labels: maintenance

#6410 ENH/CLN: Improve diagnostics
  docs/source/stats.rst
  statsmodels/examples/ex_arch_canada.py
  statsmodels/multivariate/pca.py
  statsmodels/sandbox/examples/ex_cusum.py
  statsmodels/sandbox/stats/diagnostic.py
  statsmodels/sandbox/tools/mctools.py
  statsmodels/sandbox/tools/try_mctools.py
  statsmodels/stats/_adnorm.py
  statsmodels/stats/_lilliefors.py
  statsmodels/stats/api.py
  statsmodels/stats/diagnostic.py
  statsmodels/stats/tests/test_diagnostic.py
  statsmodels/tsa/ar_model.py
  statsmodels/tsa/statespace/mlemodel.py
Labels: comp-stats, type-enh

#6424 REF: More descriptive error message for recursive least squares parameter constraints.
  statsmodels/regression/recursive_ls.py
  statsmodels/regression/tests/test_recursive_ls.py
Labels: comp-tsa-statespace, type-refactor

#6422 BUG: Improve executable detection
  statsmodels/tests/test_package.py
Labels: type-bug, type-test

#6452 DOC: Fix the version that appears in the documentaion
  docs/source/conf.py
Labels: Documentation, comp-docs

#6456 DOC: Send log to dev/null/
  tools/ci/docbuild.sh
Labels: Documentation, comp-docs

#6466 MAINT: Replace Python 3.5 with 3.8 on Azure
  azure-pipelines.yml
  tools/ci/azure_template.yml
Labels: maintenance

#6473 MAINT: Avoid future error
  statsmodels/stats/libqsturng/qsturng_.py
  statsmodels/stats/tests/test_pairwise.py
Labels: maintenance

#6474 BLD: Use pip on Azure
  .travis.yml
  pyproject.toml
  tools/ci/azure_template.yml
Labels: build, maintenance, type-test

#6411 ENH: state space: add Chandrasekhar recursions
  docs/source/_static/images/statespace_chandrasekhar.png
  docs/source/examples/landing.yml
  examples/notebooks/statespace_chandrasekhar.ipynb
  statsmodels/tsa/statespace/_filters/_conventional.pxd
  statsmodels/tsa/statespace/_filters/_conventional.pyx.in
  statsmodels/tsa/statespace/_filters/_univariate.pxd
  statsmodels/tsa/statespace/_filters/_univariate.pyx.in
  statsmodels/tsa/statespace/_kalman_filter.pxd
  statsmodels/tsa/statespace/_kalman_filter.pyx.in
  statsmodels/tsa/statespace/kalman_filter.py
  statsmodels/tsa/statespace/mlemodel.py
  statsmodels/tsa/statespace/tests/test_chandrasekhar.py
  statsmodels/tsa/statespace/tests/test_options.py
Labels: Performance, comp-tsa-statespace, type-enh

#6470 BUG: fix tukey-hsd for 1 pvalue
  statsmodels/sandbox/stats/multicomp.py
Labels: backport, comp-stats, type-bug, type-enh

#6477 BUG: Silence expected visible deprecation warning
  docs/source/examples/landing.yml
  statsmodels/graphics/tests/test_boxplots.py
  statsmodels/stats/tests/test_diagnostic.py
Labels: backport, maintenance
