Repository statsmodels/statsmodels, pull requests merged in 2022-02, with the labels that each got.

#8082 [maintenance/0.13.x] Merge pull request #7946 from bashtage/remove-looseversion
  requirements.txt
  setup.py
  statsmodels/compat/numpy.py
  statsmodels/compat/pandas.py
  statsmodels/compat/scipy.py
  statsmodels/tools/_testing.py
Labels: maintenance

#8083 MAINT: Cleanup CI
  tools/ci/azure/install-posix.sh
Labels: maintenance

#8085 MAINT: Correct backport errors
  statsmodels/base/tests/test_generic_methods.py
  statsmodels/compat/pytest.py
  statsmodels/compat/tests/test_pandas.py
  statsmodels/distributions/copula/tests/test_copula.py
  statsmodels/graphics/functional.py
  statsmodels/regression/tests/test_regression.py
  statsmodels/regression/tests/test_rolling.py
  statsmodels/tsa/base/tests/test_tsa_indexes.py
  statsmodels/tsa/base/tsa_model.py
  statsmodels/tsa/deterministic.py
  statsmodels/tsa/forecasting/theta.py
  statsmodels/tsa/holtwinters/tests/test_holtwinters.py
  statsmodels/tsa/statespace/mlemodel.py
  statsmodels/tsa/statespace/tests/test_mlemodel.py
  statsmodels/tsa/statespace/tests/test_news.py
  statsmodels/tsa/statespace/tests/test_sarimax.py
  statsmodels/tsa/tests/test_ar.py
  statsmodels/tsa/tests/test_deterministic.py
  statsmodels/tsa/vector_ar/tests/test_var_jmulti.py
  statsmodels/tsa/vector_ar/tests/test_vecm.py
  statsmodels/tsa/x13.py
Labels: maintenance

#8089 MAINT: Correct small future issues
  appveyor.yml.bak
  statsmodels/graphics/tests/test_functional.py
  tools/ci/azure/azure_template_posix.yml
  tools/ci/run_test.bat
Labels: maintenance

#8092 MAINT: Correct setup for oldest supported
  setup.py
Labels: maintenance

#8086 BUG: denominator needs to be a vector
  statsmodels/sandbox/distributions/multivariate.py
Labels: comp-distributions, type-bug

#8093 BUG: use nobs ratio in power and samplesize proportions_2indep
  statsmodels/stats/proportion.py
  statsmodels/stats/tests/test_proportion.py
Labels: comp-stats, type-bug-wrong, backport maintenance/0.13.x

#8130 BUG: Ensure exog is well specified
  statsmodels/stats/diagnostic.py
  statsmodels/stats/tests/test_diagnostic.py
Labels: type-bug, comp-stats
