Repository statsmodels/statsmodels, pull requests merged in 2023-05, with the labels that each got.

#8845 BUG/ENH: support offset in truncated count models
  statsmodels/discrete/discrete_model.py
  statsmodels/discrete/tests/test_truncated_model.py
  statsmodels/discrete/truncated_model.py
  statsmodels/robust/tests/test_norms.py
Labels: type-bug, type-enh, comp-discrete, backport

#8861 DOC: Fix internet address of dataset
  examples/notebooks/statespace_sarimax_internet.ipynb
Labels: comp-docs

#8862 DOC: Small additional fixes
  docs/source/release/version0.14.rst
  statsmodels/distributions/copula/copulas.py
  statsmodels/robust/norms.py
  statsmodels/tsa/statespace/kalman_filter.py
  statsmodels/tsa/statespace/simulation_smoother.py
Labels: comp-docs

#8863 DOC: Add version
  docs/source/conf.py
Labels: Documentation

#8875 TST: Relax tolerance on overly tight test
  statsmodels/robust/tests/test_norms.py
Labels: backport maintenance/0.14.x
